services:
  api:
    container_name: "toatoa-api"
    image: ${PRIVATE_REGISTRY_IMAGENAME}:latest
    ports:
      - "${HOST_PORT:-8080}:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__ORACLECONNSTR_ToAToaDb: ${ORACLECONNSTR_ToAToaDb}
      ReverseProxy__KnownProxies__0: ${REVERSE_PROXY_IP:-}
    volumes:
      - "${ORACLE_WALLET_PATH:-/opt/toatoa/wallet}:/app/wallet:ro"
