// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ToAToa.DataAccess;

#nullable disable

namespace ToAToa.DataAccess.Migrations
{
    [DbContext(typeof(ToAToaDbContext))]
    partial class ToAToaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ToAToa.Domain.Entities.Atividade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Atividade", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Descricao = "Participar uma roda de samba"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Descricao = "Participar uma roda de choro"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Descricao = "Jogar capoeira"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Descricao = "Preparar uma feijoada"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            Descricao = "Fazer pão de queijo"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            Descricao = "Enrolar brigadeiro"
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            Descricao = "Dançar forró"
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            Descricao = "Assistir a um capítulo de uma novela"
                        },
                        new
                        {
                            Id = 9,
                            Ativo = true,
                            Descricao = "Fazer compras na feira livre"
                        },
                        new
                        {
                            Id = 10,
                            Ativo = true,
                            Descricao = "Participar de uma festa junina"
                        },
                        new
                        {
                            Id = 11,
                            Ativo = true,
                            Descricao = "Aprender a tocar cavaquinho"
                        },
                        new
                        {
                            Id = 12,
                            Ativo = true,
                            Descricao = "Aprender a tocar violão"
                        },
                        new
                        {
                            Id = 13,
                            Ativo = true,
                            Descricao = "Fazer um churrasco"
                        },
                        new
                        {
                            Id = 14,
                            Ativo = true,
                            Descricao = "Visitar uma escola de samba"
                        },
                        new
                        {
                            Id = 15,
                            Ativo = true,
                            Descricao = "Fazer pão de queijo"
                        },
                        new
                        {
                            Id = 16,
                            Ativo = true,
                            Descricao = "Assistir a um jogo de futebol"
                        },
                        new
                        {
                            Id = 17,
                            Ativo = true,
                            Descricao = "Assistir a um jogo de futebol de botão"
                        },
                        new
                        {
                            Id = 18,
                            Ativo = true,
                            Descricao = "Assistir a um jogo de futsal"
                        },
                        new
                        {
                            Id = 19,
                            Ativo = true,
                            Descricao = "Assistir a um jogo de vôlei"
                        },
                        new
                        {
                            Id = 20,
                            Ativo = true,
                            Descricao = "Jogar uma partida de futebol"
                        },
                        new
                        {
                            Id = 21,
                            Ativo = true,
                            Descricao = "Jogar uma partida de futebol de botão"
                        },
                        new
                        {
                            Id = 22,
                            Ativo = true,
                            Descricao = "Jogar uma partida de futsal"
                        },
                        new
                        {
                            Id = 23,
                            Ativo = true,
                            Descricao = "Jogar uma partida de vôlei"
                        },
                        new
                        {
                            Id = 24,
                            Ativo = true,
                            Descricao = "Fazer uma trilha na mata atlântica"
                        },
                        new
                        {
                            Id = 25,
                            Ativo = true,
                            Descricao = "Fazer uma trilha no pantanal"
                        },
                        new
                        {
                            Id = 26,
                            Ativo = true,
                            Descricao = "Fazer uma trilha no cerrado"
                        },
                        new
                        {
                            Id = 27,
                            Ativo = true,
                            Descricao = "Fazer uma trilha na floresta amazônica"
                        },
                        new
                        {
                            Id = 28,
                            Ativo = true,
                            Descricao = "Fazer uma trilha no pampa"
                        },
                        new
                        {
                            Id = 29,
                            Ativo = true,
                            Descricao = "Fazer uma trilha na caatinga"
                        },
                        new
                        {
                            Id = 30,
                            Ativo = true,
                            Descricao = "Fazer um passeio de barco no pantanal"
                        },
                        new
                        {
                            Id = 31,
                            Ativo = true,
                            Descricao = "Participar de um bloco de carnaval"
                        },
                        new
                        {
                            Id = 32,
                            Ativo = true,
                            Descricao = "Ir a um festival de música sertaneja"
                        },
                        new
                        {
                            Id = 33,
                            Ativo = true,
                            Descricao = "Ir a um festival e MPB"
                        },
                        new
                        {
                            Id = 34,
                            Ativo = true,
                            Descricao = "Visitar uma plantação de soja"
                        },
                        new
                        {
                            Id = 35,
                            Ativo = true,
                            Descricao = "Visitar uma plantação de milho"
                        },
                        new
                        {
                            Id = 36,
                            Ativo = true,
                            Descricao = "Visitar uma plantaçao de cana-de-açúcar"
                        },
                        new
                        {
                            Id = 37,
                            Ativo = true,
                            Descricao = "Visitar uma vinícola"
                        },
                        new
                        {
                            Id = 38,
                            Ativo = true,
                            Descricao = "Visitar uma fábrica de cachaça"
                        },
                        new
                        {
                            Id = 39,
                            Ativo = true,
                            Descricao = "Visitar uma fábrica de rapadura"
                        },
                        new
                        {
                            Id = 40,
                            Ativo = true,
                            Descricao = "Visitar um alambique"
                        },
                        new
                        {
                            Id = 41,
                            Ativo = true,
                            Descricao = "Visitar um engenho"
                        },
                        new
                        {
                            Id = 42,
                            Ativo = true,
                            Descricao = "Visitar uma fábrica de cerveja artesanal"
                        },
                        new
                        {
                            Id = 43,
                            Ativo = true,
                            Descricao = "Visitar um mercado de artesanato"
                        },
                        new
                        {
                            Id = 44,
                            Ativo = true,
                            Descricao = "Assistir a uma peça de teatro"
                        },
                        new
                        {
                            Id = 45,
                            Ativo = true,
                            Descricao = "Fazer um passeio de trem"
                        },
                        new
                        {
                            Id = 46,
                            Ativo = true,
                            Descricao = "Participar de uma corrida de rua"
                        },
                        new
                        {
                            Id = 47,
                            Ativo = true,
                            Descricao = "Plantar uma árvore"
                        },
                        new
                        {
                            Id = 48,
                            Ativo = true,
                            Descricao = "Fazer tapioca"
                        },
                        new
                        {
                            Id = 49,
                            Ativo = true,
                            Descricao = "Visitar uma cachoeira"
                        },
                        new
                        {
                            Id = 50,
                            Ativo = true,
                            Descricao = "Tomar um cafezinho"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
