CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241013160557_Initial') THEN
    CREATE TABLE "Atividade" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Descricao" text NOT NULL,
        "Ativo" boolean NOT NULL,
        CONSTRAINT "PK_Atividade" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241013160557_Initial') THEN
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (1, TRUE, 'Participar uma roda de samba');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (2, TRUE, 'Participar uma roda de choro');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (3, TRUE, 'Jogar capoeira');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (4, TRUE, 'Preparar uma feijoada');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (5, TRUE, 'Fazer pão de queijo');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (6, TRUE, 'Enrolar brigadeiro');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (7, TRUE, 'Dançar forró');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (8, TRUE, 'Assistir a um capítulo de uma novela');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (9, TRUE, 'Fazer compras na feira livre');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (10, TRUE, 'Participar de uma festa junina');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (11, TRUE, 'Aprender a tocar cavaquinho');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (12, TRUE, 'Aprender a tocar violão');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (13, TRUE, 'Fazer um churrasco');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (14, TRUE, 'Visitar uma escola de samba');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (15, TRUE, 'Fazer pão de queijo');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (16, TRUE, 'Assistir a um jogo de futebol');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (17, TRUE, 'Assistir a um jogo de futebol de botão');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (18, TRUE, 'Assistir a um jogo de futsal');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (19, TRUE, 'Assistir a um jogo de vôlei');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (20, TRUE, 'Jogar uma partida de futebol');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (21, TRUE, 'Jogar uma partida de futebol de botão');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (22, TRUE, 'Jogar uma partida de futsal');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (23, TRUE, 'Jogar uma partida de vôlei');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (24, TRUE, 'Fazer uma trilha na mata atlântica');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (25, TRUE, 'Fazer uma trilha no pantanal');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (26, TRUE, 'Fazer uma trilha no cerrado');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (27, TRUE, 'Fazer uma trilha na floresta amazônica');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (28, TRUE, 'Fazer uma trilha no pampa');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (29, TRUE, 'Fazer uma trilha na caatinga');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (30, TRUE, 'Fazer um passeio de barco no pantanal');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (31, TRUE, 'Participar de um bloco de carnaval');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (32, TRUE, 'Ir a um festival de música sertaneja');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (33, TRUE, 'Ir a um festival e MPB');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (34, TRUE, 'Visitar uma plantação de soja');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (35, TRUE, 'Visitar uma plantação de milho');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (36, TRUE, 'Visitar uma plantaçao de cana-de-açúcar');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (37, TRUE, 'Visitar uma vinícola');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (38, TRUE, 'Visitar uma fábrica de cachaça');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (39, TRUE, 'Visitar uma fábrica de rapadura');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (40, TRUE, 'Visitar um alambique');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (41, TRUE, 'Visitar um engenho');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (42, TRUE, 'Visitar uma fábrica de cerveja artesanal');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (43, TRUE, 'Visitar um mercado de artesanato');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (44, TRUE, 'Assistir a uma peça de teatro');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (45, TRUE, 'Fazer um passeio de trem');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (46, TRUE, 'Participar de uma corrida de rua');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (47, TRUE, 'Plantar uma árvore');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (48, TRUE, 'Fazer tapioca');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (49, TRUE, 'Visitar uma cachoeira');
    INSERT INTO "Atividade" ("Id", "Ativo", "Descricao")
    VALUES (50, TRUE, 'Tomar um cafezinho');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241013160557_Initial') THEN
    PERFORM setval(
        pg_get_serial_sequence('"Atividade"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Atividade") + 1,
            nextval(pg_get_serial_sequence('"Atividade"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241013160557_Initial') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20241013160557_Initial', '8.0.10');
    END IF;
END $EF$;
COMMIT;

