name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  sonarcloud:
    runs-on: windows-latest
    steps:
      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Verificar código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache de pacotes SonarCloud
        uses: actions/cache@v4
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache do scanner SonarCloud
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      - name: Instalar scanner do SonarCloud
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner

      - name: Compilar e analisar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"obrennomartins_toatoa" /o:"obrennomartins" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="TestResults/**/coverage.opencover.xml"
          dotnet build
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

  codacy:
    runs-on: ubuntu-latest
    needs: sonarcloud
    steps:
      - name: Verificar código
        uses: actions/checkout@v3

      - name: Instalar .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependências
        run: dotnet restore

      - name: Executar testes unitários com cobertura
        run: dotnet test --configuration Release --collect:"XPlat Code Coverage" --results-directory ./TestResults

      - name: Instalar ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Gerar relatório de cobertura no formato Cobertura
        run: |
          reportgenerator "-reports:./TestResults/**/coverage.cobertura.xml" "-targetdir:./TestResults/CoverageReport" -reporttypes:Cobertura

      - name: Upload de cobertura de testes para o Codacy
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r ./TestResults/CoverageReport/Cobertura.xml

  docker:
    runs-on: ubuntu-latest
    needs: codacy
    steps:
      - name: Checar código
        uses: actions/checkout@v3

      - name: Definir variáveis de metadados
        id: vars
        run: |
          echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV
          echo "GIT_AUTHOR=$(git log -1 --pretty=format:'%an')" >> $GITHUB_ENV
          echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Construir imagem Docker
        run: |
          docker build -t ${{ secrets.CONTAINER_REGISTRY_ADDRESS }}/${{ secrets.CONTAINER_REGISTRY_NAMESPACE }}/${{ secrets.CONTAINER_REGISTRY_IMAGE_NAME }}:${{ env.BRANCH_NAME }}-${{ env.COMMIT_HASH }} \
                        --label "org.opencontainers.image.created=${{ env.BUILD_DATE }}" \
                        --label "org.opencontainers.image.revision=${{ env.COMMIT_HASH }}" \
                        --label "org.opencontainers.image.source=${{ github.repository }}" \
                        --label "org.opencontainers.image.authors=${{ env.GIT_AUTHOR }}" \
                        --label "org.opencontainers.image.title=${{ github.event.repository.name }}" \
                        --label "org.opencontainers.image.description=${{ env.COMMIT_MESSAGE }}" .

      - name: Entrar no registro 
        run: echo "${{ secrets.CONTAINER_REGISTRY_PASSWORD }}" | docker login ${{ secrets.CONTAINER_REGISTRY_ADDRESS }} -u "${{ secrets.CONTAINER_REGISTRY_USERNAME }}" --password-stdin

      - name: Enviar imagem para registro
        run: docker push ${{ secrets.CONTAINER_REGISTRY_ADDRESS }}/${{ secrets.CONTAINER_REGISTRY_NAMESPACE }}/${{ secrets.CONTAINER_REGISTRY_IMAGE_NAME }}:${{ env.BRANCH_NAME }}-${{ env.COMMIT_HASH }}