name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  sonarcloud:
    runs-on: windows-latest
    steps:
      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Verificar código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache de pacotes SonarCloud
        uses: actions/cache@v4
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache do scanner SonarCloud
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      - name: Instalar scanner do SonarCloud
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner

      - name: Compilar e analisar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"obrennomartins_toatoa" /o:"obrennomartins" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="TestResults/**/coverage.opencover.xml"
          dotnet build ToAToa.sln --no-incremental -c Release
          dotnet test ToAToa.sln --no-build --configuration Release --collect:"XPlat Code Coverage" --results-directory TestResults --logger "trx;LogFileName=unittests.trx" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

  codacy:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar código
        uses: actions/checkout@v3

      - name: Instalar .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependências
        run: dotnet restore

      - name: Executar testes e gerar cobertura para Codacy
        run: dotnet test --configuration Release --collect:"XPlat Code Coverage" --results-directory ./TestResults

      - name: Upload de cobertura de testes para o Codacy
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          # O script do Codacy procura pelo arquivo coverage.xml no formato 'cobertura'
          # O comando 'dotnet test' acima gera 'coverage.cobertura.xml', então precisamos encontrar o caminho exato
          COVERAGE_FILE=$(find ./TestResults -name "coverage.cobertura.xml")
          echo "Encontrado arquivo de cobertura em: $COVERAGE_FILE"
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r $COVERAGE_FILE

  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.2
        with:
          pr-mode: false
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
          QODANA_ENDPOINT: 'https://qodana.cloud'

  docker:
    runs-on: ubuntu-latest
    needs: 
      - sonarcloud
      - codacy
      - qodana
    steps:
      - name: Checar código
        uses: actions/checkout@v3

      - name: Definir variáveis de metadados
        id: vars
        run: |
          echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV
          echo "GIT_AUTHOR=$(git log -1 --pretty=format:'%an')" >> $GITHUB_ENV
          echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Construir imagem Docker
        run: |
          docker build -t ${{ secrets.CONTAINER_REGISTRY_ADDRESS }}/${{ secrets.CONTAINER_REGISTRY_NAMESPACE }}/${{ secrets.CONTAINER_REGISTRY_IMAGE_NAME }}:${{ env.BRANCH_NAME }} \
                       -t ${{ secrets.CONTAINER_REGISTRY_ADDRESS }}/${{ secrets.CONTAINER_REGISTRY_NAMESPACE }}/${{ secrets.CONTAINER_REGISTRY_IMAGE_NAME }}:latest \
                       --label "org.opencontainers.image.created=${{ env.BUILD_DATE }}" \
                       --label "org.opencontainers.image.source=${{ github.repository }}" \
                       --label "org.opencontainers.image.authors=${{ env.GIT_AUTHOR }}" \
                       --label "org.opencontainers.image.title=${{ github.event.repository.name }}" \
                       --label "org.opencontainers.image.description=${{ env.COMMIT_MESSAGE }}" .

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Aciona webhook do Portainer
        run: |
          curl -X POST ${{ secrets.PORTAINER_WEBHOOK_URL }}
